export const coursesData = {
  "7C": {
    courseName: "Séptimo C",
    students: [
      {
        name: "Alfonso Gajardo Cristóbal Andrés",
        rut: "241334481",
        listening: { score: 36, level: "A1" },
        reading: { score: 50, level: "A2" },
        writing: { score: 60, level: "A2" },
        speaking: { score: 90, level: "Towards B2" },
        overall: { score: 59, level: "A2" },
      },
      {
        name: "Arenas Arzola Maite Trinidad",
        rut: "242127242",
        listening: { score: 56, level: "A2" },
        reading: { score: 13, level: "A1" },
        writing: { score: 38, level: "A1" },
        speaking: { score: 85, level: "B1" },
        overall: { score: 48, level: "A2" },
      },
      {
        name: "Baeza Díaz Nicolás Adolfo",
        rut: "240204282",
        listening: { score: 48, level: "A2" },
        reading: { score: 6, level: "A1" },
        writing: { score: 0, level: "A1" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 39, level: "A1" },
      },
      {
        name: "Barrera Miranda Michelle Amelia",
        rut: "241013456",
        listening: { score: 48, level: "A2" },
        reading: { score: 44, level: "A1" },
        writing: { score: 58, level: "A2" },
        speaking: { score: 80, level: "B1" },
        overall: { score: 57, level: "A2" },
      },
      {
        name: "Benko Cueto Gabriela Rosario",
        rut: "239755364",
        listening: { score: 60, level: "A2" },
        reading: { score: 41, level: "A1" },
        writing: { score: 40, level: "A1" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 60, level: "A2" },
      },
      {
        name: "Bravo Gutiérrez Florencia Ignacia",
        rut: "239598404",
        listening: { score: 92, level: "Towards B2" },
        reading: { score: 97, level: "Towards B2" },
        writing: { score: 70, level: "B1" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 90, level: "Towards B2" },
      },
      {
        name: "Brücher Miqueles Laura Dominga",
        rut: "239759785",
        listening: { score: 68, level: "A2" },
        reading: { score: 78, level: "B1" },
        writing: { score: 68, level: "A2" },
        speaking: { score: 90, level: "Towards B2" },
        overall: { score: 76, level: "B1" },
      },
      {
        name: "Cervellino Contreras Gianluca Enzo",
        rut: "241829766",
        listening: { score: 20, level: "A1" },
        reading: { score: 69, level: "A2" },
        writing: { score: 25, level: "A1" },
        speaking: { score: 90, level: "Towards B2" },
        overall: { score: 51, level: "A2" },
      },
      {
        name: "Charme Puga Julieta Isidora",
        rut: "23993661K",
        listening: { score: 56, level: "A2" },
        reading: { score: 56, level: "A2" },
        writing: { score: 35, level: "A2" },
        speaking: { score: 90, level: "B1" },
        overall: { score: 66, level: "A2" },
      },
      {
        name: "Contreras Ortega Juan Pablo",
        rut: "240344513",
        listening: { score: 47, level: "A2" },
        reading: { score: 47, level: "A2" },
        writing: { score: 40, level: "A1" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 62, level: "A2" },
      },
      {
        name: "Contreras Vera Javier Ignacio",
        rut: "242122895",
        listening: { score: 56, level: "A2" },
        reading: { score: 88, level: "B1" },
        writing: { score: 55, level: "A2" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 73, level: "B1" },
      },
      {
        name: "Corral Gallardo Agustín Esteban",
        rut: "238927552",
        listening: { score: 52, level: "A2" },
        reading: { score: 28, level: "A1" },
        writing: { score: 75, level: "B1" },
        speaking: { score: 85, level: "B1" },
        overall: { score: 60, level: "A2" },
      },
      {
        name: "Delgado Rojas David Rafael",
        rut: "241815773",
        listening: { score: 68, level: "A2" },
        reading: { score: 53, level: "A2" },
        writing: { score: 75, level: "B1" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 74, level: "B1" },
      },
      {
        name: "Espinoza Piñeiro Tomás Alonso",
        rut: "239492312",
        listening: { score: 84, level: "B1" },
        reading: { score: 91, level: "Towards B2" },
        writing: { score: 35, level: "A1" },
        speaking: { score: 85, level: "B1" },
        overall: { score: 74, level: "B1" },
      },
      {
        name: "Esteves Tovar Ainhoa",
        rut: "264930804",
        listening: { score: 72, level: "B1" },
        reading: { score: 41, level: "A1" },
        writing: { score: 20, level: "A1" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 58, level: "A2" },
      },
      {
        name: "Estrada Torres Agustín Alonso",
        rut: "241410021",
        listening: { score: 72, level: "B1" },
        reading: { score: 31, level: "A1" },
        writing: { score: 38, level: "A1" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 59, level: "A2" },
      },
      {
        name: "Forti Melo Arthur",
        rut: "27098066K",
        listening: { score: 91, level: "B1" },
        reading: { score: 91, level: "Towards B2" },
        writing: { score: 68, level: "A2" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 83, level: "B1" },
      },
      {
        name: "Fuentes Díaz Lucas Andrés",
        rut: "241936066",
        listening: { score: 60, level: "A2" },
        reading: { score: 78, level: "B1" },
        writing: { score: 23, level: "A1" },
        speaking: { score: 85, level: "B1" },
        overall: { score: 61, level: "A2" },
      },
      {
        name: "Guerra Figueroa Trinidad Catalina",
        rut: "239257674",
        listening: { score: 64, level: "A2" },
        reading: { score: 50, level: "A2" },
        writing: { score: 33, level: "A1" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 62, level: "A2" },
      },
      {
        name: "Guerra Lorca Alonso Tomás",
        rut: "239174418",
        listening: { score: 80, level: "B1" },
        reading: { score: 84, level: "B1" },
        writing: { score: 58, level: "A2" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 79, level: "B1" },
      },
      {
        name: "Maldonado Gutiérrez Sofía Antonia",
        rut: "241369846",
        listening: { score: 88, level: "B1" },
        reading: { score: 97, level: "Towards B2" },
        writing: { score: 88, level: "B1" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 92, level: "Towards B2" },
      },
      {
        name: "Mestre Moya Antonio Miguel",
        rut: "239315836",
        listening: { score: 12, level: "A1" },
        reading: { score: 25, level: "A1" },
        writing: { score: 49, level: "A2" },
        speaking: { score: 95, level: "B1" },
        overall: { score: 44, level: "A1" },
      },
      {
        name: "Montero Cepeda Sofía Antonia",
        rut: "242166779",
        listening: { score: 48, level: "A2" },
        reading: { score: 47, level: "A2" },
        writing: { score: 23, level: "A1" },
        speaking: { score: 90, level: "B1" },
        overall: { score: 49, level: "A2" },
      },
      {
        name: "Moreau Muñoz Catalina Paz",
        rut: "241727181",
        listening: { score: 72, level: "B1" },
        reading: { score: 63, level: "A2" },
        writing: { score: 50, level: "A2" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 70, level: "B1" },
      },
      {
        name: "Ocares Morales Trinidad Antonia",
        rut: "240120682",
        listening: { score: 64, level: "A2" },
        reading: { score: 75, level: "B1" },
        writing: { score: 35, level: "A1" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 69, level: "A2" },
      },
      {
        name: "Otegui Vergara Florencia Antonia",
        rut: "239558747",
        listening: { score: 16, level: "A1" },
        reading: { score: 19, level: "A1" },
        writing: { score: 60, level: "A2" },
        speaking: { score: 100, level: "B2" },
        overall: { score: 49, level: "A2" },
      },
      {
        name: "Polgatiz Manque Luciano Rafael",
        rut: "241235491",
        listening: { score: 80, level: "B1" },
        reading: { score: 78, level: "B1" },
        writing: { score: 58, level: "A2" },
        speaking: { score: 100, level: "B2" },
        overall: { score: 79, level: "B1" },
      },
      {
        name: "Ramírez Araya Martín Alonso",
        rut: "242243463",
        listening: { score: 68, level: "A2" },
        reading: { score: 91, level: "Towards B2" },
        writing: { score: 48, level: "A2" },
        speaking: { score: 90, level: "B2" },
        overall: { score: 74, level: "B1" },
      },
      {
        name: "Salinas Alvear Rafaela Leonor",
        rut: "241927067",
        listening: { score: 76, level: "B1" },
        reading: { score: 91, level: "Towards B2" },
        writing: { score: 50, level: "A2" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 78, level: "B1" },
      },
      {
        name: "Urrutia Guzmán Aitor",
        rut: "239943861",
        listening: { score: 68, level: "A2" },
        reading: { score: 78, level: "B1" },
        writing: { score: 28, level: "A1" },
        speaking: { score: 90, level: "Towards B2" },
        overall: { score: 66, level: "A2" },
      },
      {
        name: "Viñals Vásquez Florencia",
        rut: "241750485",
        listening: { score: 80, level: "B1" },
        reading: { score: 84, level: "B1" },
        writing: { score: 88, level: "B1" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 88, level: "B1" },
      },
      {
        name: "Vásquez Rojas Josefa Antonia",
        rut: "240793466",
        listening: { score: 56, level: "A2" },
        reading: { score: 34, level: "A1" },
        writing: { score: 65, level: "A2" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 64, level: "A2" },
      },
    ],
  },
  "7D": {
    courseName: "Séptimo D",
    students: [
      {
        name: "Alvarez Gamboa Emilia Antonia",
        rut: "240253607",
        listening: { score: 72, level: "B1" },
        reading: { score: 72, level: "B1" },
        writing: { score: 70, level: "B1" },
        speaking: { score: 85, level: "B1" },
        overall: { score: 75, level: "B1" },
      },
      {
        name: "Barrientos Taivo Pedro",
        rut: "240939088",
        listening: { score: 48, level: "A2" },
        reading: { score: 59, level: "A2" },
        writing: { score: 53, level: "A2" },
        speaking: { score: 85, level: "B1" },
        overall: { score: 61, level: "A2" },
      },
      {
        name: "Cabezas Jadrijevic Vicente Alonso",
        rut: "241024695",
        listening: { score: 40, level: "A1" },
        reading: { score: 59, level: "A2" },
        writing: { score: 40, level: "A1" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 59, level: "A2" },
      },
      {
        name: "Cabrera Baez Gonzalo Javier",
        rut: "23980716K",
        listening: { score: 72, level: "B1" },
        reading: { score: 66, level: "A2" },
        writing: { score: 45, level: "A2" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 69, level: "A2" },
      },
      {
        name: "Durán Salas Rafaela Victoria",
        rut: "239511333",
        listening: { score: 76, level: "B1" },
        reading: { score: 94, level: "Towards B2" },
        writing: { score: 78, level: "B1" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 86, level: "B1" },
      },
      {
        name: "Farías Crespo Gonzalo Octavio",
        rut: "241023281",
        listening: { score: 44, level: "A1" },
        reading: { score: 47, level: "A2" },
        writing: { score: 0, level: "A1" },
        speaking: { score: 80, level: "B1" },
        overall: { score: 43, level: "A1" },
      },
      {
        name: "Garcia Vergara Agustin Gabriel",
        rut: "241621014",
        listening: { score: 24, level: "A1" },
        reading: { score: 41, level: "A1" },
        writing: { score: 50, level: "A2" },
        speaking: { score: 90, level: "Towards B2" },
        overall: { score: 51, level: "A2" },
      },
      {
        name: "Garrido Tapia Antonia",
        rut: "240672154",
        listening: { score: 48, level: "A2" },
        reading: { score: 28, level: "A1" },
        writing: { score: 30, level: "A1" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 50, level: "A2" },
      },
      {
        name: "Medina Alruiz Franco Lorenzo",
        rut: "24200289K",
        listening: { score: 52, level: "A2" },
        reading: { score: 38, level: "A1" },
        writing: { score: 20, level: "A1" },
        speaking: { score: 80, level: "B1" },
        overall: { score: 47, level: "A2" },
      },
      {
        name: "Moreno Hidrovo Diego Antonio",
        rut: "26155884K",
        listening: { score: 16, level: "A1" },
        reading: { score: 3, level: "A1" },
        writing: { score: 18, level: "A1" },
        speaking: { score: 70, level: "B1" },
        overall: { score: 27, level: "A1" },
      },
      {
        name: "Picero Silva Laura Fernanda",
        rut: "239904181",
        listening: { score: 88, level: "B1" },
        reading: { score: 91, level: "Towards B2" },
        writing: { score: 63, level: "A2" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 85, level: "B1" },
      },
      {
        name: "Poblete Bravo Florencia Carolina",
        rut: "240201003",
        listening: { score: 84, level: "B1" },
        reading: { score: 100, level: "Towards B2" },
        writing: { score: 78, level: "B1" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 90, level: "Towards B2" },
      },
      {
        name: "Pérez Cornejo Emma Josefa",
        rut: "24013991K",
        listening: { score: 64, level: "A2" },
        reading: { score: 53, level: "A2" },
        writing: { score: 23, level: "A1" },
        speaking: { score: 95, level: "B1" },
        overall: { score: 59, level: "A2" },
      },
      {
        name: "Quinlan Briceño Colomba",
        rut: "241756521",
        listening: { score: 46, level: "A2" },
        reading: { score: 53, level: "A2" },
        writing: { score: 53, level: "A2" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 61, level: "A2" },
      },
      {
        name: "Rojas Henriquez Emilia Javiera",
        rut: "239658482",
        listening: { score: 84, level: "B1" },
        reading: { score: 91, level: "Towards B2" },
        writing: { score: 100, level: "Towards B2" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 94, level: "Towards B2" },
      },
      {
        name: "Rojas Mena Gaspar Andrés",
        rut: "239890105",
        listening: { score: 40, level: "A1" },
        reading: { score: 19, level: "A1" },
        writing: { score: 28, level: "A1" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 45, level: "A2" },
      },
      {
        name: "Ruiz Cortes Catalina Ignacia",
        rut: "240823756",
        listening: { score: 84, level: "B1" },
        reading: { score: 91, level: "Towards B2" },
        writing: { score: 88, level: "B1" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 91, level: "Towards B2" },
      },
      {
        name: "Sepúlveda Orrego Sofía Ignacia",
        rut: "23940491K",
        listening: { score: 68, level: "A2" },
        reading: { score: 81, level: "B1" },
        writing: { score: 95, level: "Towards B2" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 86, level: "B1" },
      },
      {
        name: "Toro Novoa Joaquin Nicolas",
        rut: "239301991",
        listening: { score: 44, level: "A1" },
        reading: { score: 31, level: "A1" },
        writing: { score: 38, level: "A1" },
        speaking: { score: 85, level: "B1" },
        overall: { score: 49, level: "A2" },
      },
      {
        name: "Valdebenito Salazar Tomas Alonso",
        rut: "23924551K",
        listening: { score: 92, level: "Towards B2" },
        reading: { score: 97, level: "Towards B2" },
        writing: { score: 85, level: "B1" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 93, level: "Towards B2" },
      },
      {
        name: "Vega Vera Laura Carolina",
        rut: "240644894",
        listening: { score: 88, level: "B1" },
        reading: { score: 100, level: "Towards B2" },
        writing: { score: 100, level: "Towards B2" },
        speaking: { score: 100, level: "Towards B2" },
        overall: { score: 97, level: "Towards B2" },
      },
      {
        name: "Majluf Badilla Nicolas Enrique",
        rut: "24042732K",
        listening: { score: 40, level: "A1" },
        reading: { score: 28, level: "A1" },
        writing: { score: 28, level: "A1" },
        speaking: { score: 0, level: "" },
        overall: { score: 0, level: "" },
      },
      {
        name: "Stevens Arévalo Lucas Mario",
        rut: "239535798",
        listening: { score: 72, level: "B1" },
        reading: { score: 59, level: "A2" },
        writing: { score: 25, level: "A1" },
        speaking: { score: 0, level: "" },
        overall: { score: 0, level: "" },
      },
      {
        name: "Illanes Donato Trinidad Catalina",
        rut: "242291999",
        listening: { score: 0, level: "" },
        reading: { score: 0, level: "" },
        writing: { score: 0, level: "" },
        speaking: { score: 95, level: "Towards B2" },
        overall: { score: 0, level: "" },
      },
    ],
  },
  "6C": {
    courseName: "Sexto C",
    students: [
      {
        name: "Aburto Carreño Mateo Daniel",
        rut: "24410438K",
        listening: { score: 64, level: "Towards A2" },
        reading: { score: 63, level: "Towards A2" },
        writing: { score: 43, level: "A1" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 66, level: "Towards A2" },
      },
      {
        name: "Aspe Campos Camilo",
        rut: "242781058",
        listening: { score: 80, level: "A2" },
        reading: { score: 60, level: "Towards A2" },
        writing: { score: 47, level: "A2" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 70, level: "A2" },
      },
      {
        name: "Barrientos Van de Wiele Alicia Ines",
        rut: "24396914K",
        listening: { score: 92, level: "Towards B1" },
        reading: { score: 87, level: "A2" },
        writing: { score: 73, level: "A2" },
        speaking: { score: 80, level: "A2" },
        overall: { score: 83, level: "A2" },
      },
      {
        name: "Bonacic Planzer Franz",
        rut: "240483025",
        listening: { score: 88, level: "A2" },
        reading: { score: 87, level: "A2" },
        writing: { score: 60, level: "A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 84, level: "A2" },
      },
      {
        name: "Calderon Valdes Pascale Belen",
        rut: "243222915",
        listening: { score: 72, level: "A2" },
        reading: { score: 71, level: "A2" },
        writing: { score: 27, level: "A1" },
        speaking: { score: 81, level: "A2" },
        overall: { score: 66, level: "Towards A2" },
      },
      {
        name: "Contreras Acuña Trinidad Amalia",
        rut: "244578993",
        listening: { score: 41, level: "A1" },
        reading: { score: 13, level: "A1" },
        writing: { score: 23, level: "A1" },
        speaking: { score: 51, level: "A1" },
        overall: { score: 19, level: "A1" },
      },
      {
        name: "Contreras Moreno Alonso Ignacio",
        rut: "244355056",
        listening: { score: 72, level: "A2" },
        reading: { score: 57, level: "Towards A2" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 69, level: "A2" },
      },
      {
        name: "Correa Andaur David Alejandro",
        rut: "242882318",
        listening: { score: 92, level: "B1" },
        reading: { score: 73, level: "A2" },
        writing: { score: 67, level: "A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 80, level: "A2" },
      },
      {
        name: "de la Fuente Salazar Matias Rodrigo",
        rut: "243990513",
        listening: { score: 36, level: "A1" },
        reading: { score: 50, level: "Towards A2" },
        writing: { score: 20, level: "A1" },
        speaking: { score: 53, level: "Towards A2" },
        overall: { score: 40, level: "A1" },
      },
      {
        name: "Farmer Kubat Raimundo Gaspar",
        rut: "24358325K",
        listening: { score: 64, level: "Towards A2" },
        reading: { score: 70, level: "A2" },
        writing: { score: 47, level: "Towards A2" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 69, level: "Towards A2" },
      },
      {
        name: "Fenerías Morales Isidora Francisca",
        rut: "242371828",
        listening: { score: 76, level: "A2" },
        reading: { score: 90, level: "Towards B1" },
        writing: { score: 67, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 83, level: "A2" },
      },
      {
        name: "Fornes Zubicueta Martina Paz",
        rut: "244779336",
        listening: { score: 44, level: "A1" },
        reading: { score: 41, level: "A1" },
        writing: { score: 21, level: "A1" },
        speaking: { score: 73, level: "A2" },
        overall: { score: 31, level: "A1" },
      },
      {
        name: "Jorquera Gatica Maite Agustina",
        rut: "242667336",
        listening: { score: 88, level: "A2" },
        reading: { score: 83, level: "A2" },
        writing: { score: 60, level: "A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 86, level: "A2" },
      },
      {
        name: "Lavandero Camus Fernando Alberto",
        rut: "244470904",
        listening: { score: 72, level: "A2" },
        reading: { score: 73, level: "A2" },
        writing: { score: 60, level: "A2" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 75, level: "A2" },
      },
      {
        name: "Mansilla Rios Joaquin Andrés",
        rut: "244313655",
        listening: { score: 80, level: "A2" },
        reading: { score: 87, level: "A2" },
        writing: { score: 53, level: "Towards A2" },
        speaking: { score: 73, level: "A2" },
        overall: { score: 73, level: "A2" },
      },
      {
        name: "Meneses Pareja Gabriel Andrés",
        rut: "242649354",
        listening: { score: 48, level: "Towards A2" },
        reading: { score: 40, level: "A1" },
        writing: { score: 47, level: "Towards A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 55, level: "Towards A2" },
      },
      {
        name: "Méndez Garcìa Mariangel",
        rut: "251002770",
        listening: { score: 84, level: "A2" },
        reading: { score: 77, level: "A2" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 60, level: "A2" },
        overall: { score: 70, level: "A2" },
      },
      {
        name: "Núñez Díaz María Jesús",
        rut: "24473152K",
        listening: { score: 60, level: "Towards A2" },
        reading: { score: 57, level: "Towards A2" },
        writing: { score: 63, level: "Towards A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 67, level: "Towards A2" },
      },
      {
        name: "Núñez González Agustin Alonso",
        rut: "24473152K",
        listening: { score: 68, level: "Towards A2" },
        reading: { score: 67, level: "Towards A2" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 73, level: "A2" },
        overall: { score: 67, level: "Towards A2" },
      },
      {
        name: "Olea Bueno Antonia",
        rut: "242681894",
        listening: { score: 60, level: "Towards A2" },
        reading: { score: 57, level: "Towards A2" },
        writing: { score: 53, level: "Towards A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 64, level: "Towards A2" },
      },
      {
        name: "Osorio Escárate Joaquin Andrés",
        rut: "242999495",
        listening: { score: 76, level: "A2" },
        reading: { score: 77, level: "A2" },
        writing: { score: 80, level: "A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 83, level: "A2" },
      },
      {
        name: "Pineda González Martin Antonio",
        rut: "244695043",
        listening: { score: 80, level: "A2" },
        reading: { score: 70, level: "A2" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 78, level: "A2" },
      },
      {
        name: "Pizarro Hidalgo Alonso",
        rut: "242997298",
        listening: { score: 64, level: "A2" },
        reading: { score: 83, level: "A2" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 74, level: "A2" },
      },
      {
        name: "Porstmann González Sebastián",
        rut: "245462565",
        listening: { score: 60, level: "Towards A2" },
        reading: { score: 57, level: "Towards A2" },
        writing: { score: 47, level: "Towards A2" },
        speaking: { score: 53, level: "Towards A2" },
        overall: { score: 54, level: "Towards A2" },
      },
      {
        name: "Puebla Fuentelaba Santiago Alonso",
        rut: "243263980",
        listening: { score: 76, level: "A2" },
        reading: { score: 87, level: "A2" },
        writing: { score: 53, level: "A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 76, level: "A2" },
      },
      {
        name: "Quinteros Sánchez Nicolás Martín",
        rut: "242436660",
        listening: { score: 64, level: "Towards A2" },
        reading: { score: 60, level: "Towards A2" },
        writing: { score: 67, level: "A2" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 71, level: "A2" },
      },
      {
        name: "Severino Urzúa Víctor Alonso",
        rut: "244946712",
        listening: { score: 72, level: "A2" },
        reading: { score: 67, level: "A2" },
        writing: { score: 43, level: "A1" },
        speaking: { score: 80, level: "A2" },
        overall: { score: 66, level: "Towards A2" },
      },
      {
        name: "Vicuña Bajarlia Gabriel Ignacio",
        rut: "246588856",
        listening: { score: 56, level: "Towards A2" },
        reading: { score: 50, level: "Towards A2" },
        writing: { score: 47, level: "Towards A2" },
        speaking: { score: 67, level: "Towards A2" },
        overall: { score: 55, level: "Towards A2" },
      },
      {
        name: "Wall Acuña Gabriela",
        rut: "242452720",
        listening: { score: 84, level: "A2" },
        reading: { score: 93, level: "Towards B1" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 84, level: "A2" },
      },
      {
        name: "Soto Jimenez Antonia",
        rut: "241554864",
        listening: { score: 0, level: "" },
        reading: { score: 0, level: "" },
        writing: { score: 53, level: "Towards A2" },
        speaking: { score: 0, level: "" },
        overall: { score: 0, level: "" },
      },
    ],
  },
  "6D": {
    courseName: "Sexto D",
    students: [
      {
        name: "Aguirre Remedi Dominique Alejandra",
        rut: "244546749",
        listening: { score: 76, level: "A2" },
        reading: { score: 90, level: "Towards B1" },
        writing: { score: 60, level: "A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 82, level: "A2" },
      },
      {
        name: "Andrades Moreno Agustín Tomás",
        rut: "245067917",
        listening: { score: 92, level: "Towards B1" },
        reading: { score: 87, level: "A2" },
        writing: { score: 63, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 86, level: "A2" },
      },
      {
        name: "Arce Holmgren Agustín Enrique",
        rut: "244879608",
        listening: { score: 68, level: "Towards A2" },
        reading: { score: 63, level: "Towards A2" },
        writing: { score: 37, level: "A1" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 64, level: "Towards A2" },
      },
      {
        name: "Arrieta Bruno Pía Ignacia",
        rut: "243492041",
        listening: { score: 32, level: "A1" },
        reading: { score: 53, level: "Towards A2" },
        writing: { score: 0, level: "A1" },
        speaking: { score: 53, level: "Towards A2" },
        overall: { score: 35, level: "A1" },
      },
      {
        name: "Bahamondes Suárez Sebastián Ignacio",
        rut: "243168317",
        listening: { score: 83, level: "A2" },
        reading: { score: 83, level: "A2" },
        writing: { score: 63, level: "Towards A2" },
        speaking: { score: 0, level: "" },
        overall: { score: 92, level: "Towards B1" },
      },
      {
        name: "Barberis Pérez Agustín Andrés",
        rut: "244793592",
        listening: { score: 40, level: "A1" },
        reading: { score: 53, level: "Towards A2" },
        writing: { score: 43, level: "A1" },
        speaking: { score: 60, level: "Towards A2" },
        overall: { score: 49, level: "Towards A2" },
      },
      {
        name: "Carrasco Vilches Amanda Belén",
        rut: "243528437",
        listening: { score: 80, level: "A2" },
        reading: { score: 57, level: "Towards A2" },
        writing: { score: 23, level: "A1" },
        speaking: { score: 67, level: "Towards A2" },
        overall: { score: 57, level: "Towards A2" },
      },
      {
        name: "Castillo Espinoza Fernanda Ignacia",
        rut: "242119967",
        listening: { score: 76, level: "A2" },
        reading: { score: 80, level: "A2" },
        writing: { score: 50, level: "Towards A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 73, level: "A2" },
      },
      {
        name: "Castro García Santiago León",
        rut: "24343257K",
        listening: { score: 92, level: "Towards B1" },
        reading: { score: 90, level: "Towards B1" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 84, level: "A2" },
      },
      {
        name: "Escudero Torres Noah Máximo",
        rut: "245179928",
        listening: { score: 64, level: "Towards A2" },
        reading: { score: 47, level: "Towards A2" },
        writing: { score: 53, level: "Towards A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 63, level: "Towards A2" },
      },
      {
        name: "Faure Brandt Maite Sophie",
        rut: "244287700",
        listening: { score: 80, level: "A2" },
        reading: { score: 83, level: "A2" },
        writing: { score: 67, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 83, level: "A2" },
      },
      {
        name: "Fernández Golusda Josefina Ignacia",
        rut: "244211976",
        listening: { score: 72, level: "A2" },
        reading: { score: 70, level: "A2" },
        writing: { score: 57, level: "Towards A2" },
        speaking: { score: 80, level: "A2" },
        overall: { score: 70, level: "A2" },
      },
      {
        name: "García Urtubia Felipe Agustín",
        rut: "243608708",
        listening: { score: 40, level: "A1" },
        reading: { score: 33, level: "A1" },
        writing: { score: 30, level: "A1" },
        speaking: { score: 53, level: "Towards A2" },
        overall: { score: 39, level: "A1" },
      },
      {
        name: "González Sánchez Martina Ignacia",
        rut: "243380073",
        listening: { score: 0, level: "" },
        reading: { score: 0, level: "" },
        writing: { score: 53, level: "Towards A2" },
        speaking: { score: 0, level: "" },
        overall: { score: 0, level: "" },
      },
      {
        name: "Hu Wu Julián Yiyong",
        rut: "243165326",
        listening: { score: 88, level: "A2" },
        reading: { score: 90, level: "Towards B1" },
        writing: { score: 63, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 85, level: "A2" },
      },
      {
        name: "López Leiva Gabriel Antonio",
        rut: "243021936",
        listening: { score: 72, level: "A2" },
        reading: { score: 57, level: "A2" },
        writing: { score: 13, level: "A1" },
        speaking: { score: 27, level: "A1" },
        overall: { score: 42, level: "A1" },
      },
      {
        name: "Muñoz Manríquez Catalina Leonor",
        rut: "243337070",
        listening: { score: 48, level: "Towards A2" },
        reading: { score: 53, level: "Towards A2" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 60, level: "Towards A2" },
        overall: { score: 55, level: "Towards A2" },
      },
      {
        name: "Oyarzún Vergara Nicolás Antonio",
        rut: "240445387",
        listening: { score: 96, level: "Towards B1" },
        reading: { score: 87, level: "A2" },
        writing: { score: 67, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 87, level: "A2" },
      },
      {
        name: "Pantoja Pino Ignacio Álvaro",
        rut: "241926079",
        listening: { score: 88, level: "A2" },
        reading: { score: 80, level: "A2" },
        writing: { score: 47, level: "Towards A2" },
        speaking: { score: 67, level: "Towards A2" },
        overall: { score: 70, level: "A2" },
      },
      {
        name: "Peralta Muñoz Santiago Andrés",
        rut: "242854829",
        listening: { score: 76, level: "A2" },
        reading: { score: 43, level: "A1" },
        writing: { score: 47, level: "Towards A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 63, level: "Towards A2" },
      },
      {
        name: "Reszczynski Steinert Leon",
        rut: "244576842",
        listening: { score: 52, level: "Towards A2" },
        reading: { score: 52, level: "Towards A2" },
        writing: { score: 47, level: "Towards A2" },
        speaking: { score: 73, level: "A2" },
        overall: { score: 57, level: "Towards A2" },
      },
      {
        name: "Revello Navarro Bruno Ignacio",
        rut: "244356877",
        listening: { score: 72, level: "A2" },
        reading: { score: 63, level: "Towards A2" },
        writing: { score: 63, level: "Towards A2" },
        speaking: { score: 73, level: "Towards A2" },
        overall: { score: 68, level: "Towards A2" },
      },
      {
        name: "Reyes Jimenez Luciano Andres",
        rut: "243458935",
        listening: { score: 60, level: "Towards A2" },
        reading: { score: 60, level: "Towards A2" },
        writing: { score: 0, level: "A1" },
        speaking: { score: 53, level: "Towards A2" },
        overall: { score: 43, level: "A1" },
      },
      {
        name: "Rojas Galaz Simón Alonso",
        rut: "244327869",
        listening: { score: 100, level: "Towards B1" },
        reading: { score: 87, level: "A2" },
        writing: { score: 63, level: "Towards A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 84, level: "A2" },
      },
      {
        name: "Salas Hurtado Agustín Ignacio",
        rut: "243544815",
        listening: { score: 56, level: "Towards A2" },
        reading: { score: 56, level: "Towards A2" },
        writing: { score: 30, level: "A1" },
        speaking: { score: 73, level: "Towards A2" },
        overall: { score: 52, level: "Towards A2" },
      },
      {
        name: "San Martín Pérez Vicente Ignacio",
        rut: "244577997",
        listening: { score: 44, level: "A1" },
        reading: { score: 44, level: "A1" },
        writing: { score: 37, level: "A1" },
        speaking: { score: 73, level: "A2" },
        overall: { score: 49, level: "A1" },
      },
      {
        name: "Sandoval Castro Baltazar",
        rut: "243589487",
        listening: { score: 80, level: "A2" },
        reading: { score: 80, level: "A2" },
        writing: { score: 57, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 79, level: "A2" },
      },
      {
        name: "Travieso Mena Laura María",
        rut: "244021530",
        listening: { score: 63, level: "A2" },
        reading: { score: 63, level: "Towards A2" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 0, level: "" },
        overall: { score: 84, level: "A2" },
      },
      {
        name: "Vásquez Vega Diego Gabriel",
        rut: "244100414",
        listening: { score: 88, level: "A2" },
        reading: { score: 93, level: "Towards B1" },
        writing: { score: 67, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 87, level: "A2" },
      },
      {
        name: "Aguila Gonzalez Magdalena Isidora",
        rut: "243047625",
        listening: { score: 0, level: "" },
        reading: { score: 0, level: "" },
        writing: { score: 67, level: "Towards A2" },
        speaking: { score: 0, level: "" },
        overall: { score: 0, level: "" },
      },
    ],
  },
  "6E": {
    courseName: "Sexto E",
    students: [
      {
        name: "Amalia Francisca Albornoz Maldonado",
        rut: "244099491",
        listening: { score: 36, level: "A1" },
        reading: { score: 43, level: "A1" },
        writing: { score: 43, level: "A1" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 52, level: "Towards A2" },
      },
      {
        name: "Germán Alonso Alegre Ramírez",
        rut: "244631800",
        listening: { score: 0, level: "" },
        reading: { score: 0, level: "" },
        writing: { score: 0, level: "" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 0, level: "" },
      },
      {
        name: "Franco Gabriel Carvacho Valdés",
        rut: "243537932",
        listening: { score: 64, level: "Towards A2" },
        reading: { score: 37, level: "A1" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 80, level: "A2" },
        overall: { score: 60, level: "Towards A2" },
      },
      {
        name: "José Tomás Catalán Alvarado",
        rut: "244169805",
        listening: { score: 64, level: "Towards A2" },
        reading: { score: 70, level: "A2" },
        writing: { score: 47, level: "Towards A2" },
        speaking: { score: 73, level: "A2" },
        overall: { score: 64, level: "Towards A2" },
      },
      {
        name: "Catalina Sofía Chan Fu",
        rut: "243775892",
        listening: { score: 96, level: "Towards B1" },
        reading: { score: 90, level: "Towards B1" },
        writing: { score: 80, level: "A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 92, level: "Towards B1" },
      },
      {
        name: "Josefina Ignacia Concha Neira",
        rut: "245813406",
        listening: { score: 72, level: "A2" },
        reading: { score: 80, level: "A2" },
        writing: { score: 63, level: "Towards A2" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 77, level: "A2" },
      },
      {
        name: "Amaia Cuesta Valdés",
        rut: "241350312",
        listening: { score: 88, level: "A2" },
        reading: { score: 97, level: "Towards B1" },
        writing: { score: 100, level: "Towards B1" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 96, level: "Towards B1" },
      },
      {
        name: "Catalina Belén Díaz Garcés",
        rut: "246571007",
        listening: { score: 92, level: "Towards B1" },
        reading: { score: 87, level: "A2" },
        writing: { score: 63, level: "Towards A2" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 84, level: "A2" },
      },
      {
        name: "David Marcelo Espinosa Orellana",
        rut: "243170370",
        listening: { score: 84, level: "A2" },
        reading: { score: 90, level: "Towards B1" },
        writing: { score: 97, level: "Towards B1" },
        speaking: { score: 0, level: "" },
        overall: { score: 0, level: "" },
      },
      {
        name: "Javiera Ignacia de los Angeles Hauck Curinao",
        rut: "243914302",
        listening: { score: 84, level: "A2" },
        reading: { score: 77, level: "A2" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 73, level: "A2" },
        overall: { score: 74, level: "A2" },
      },
      {
        name: "Amanda Victoria Iturriaga Morales",
        rut: "244106935",
        listening: { score: 88, level: "A2" },
        reading: { score: 90, level: "Towards B1" },
        writing: { score: 67, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 86, level: "A2" },
      },
      {
        name: "Mia Renata Laborde Hurtado",
        rut: "244359388",
        listening: { score: 76, level: "A2" },
        reading: { score: 73, level: "A2" },
        writing: { score: 63, level: "Towards A2" },
        speaking: { score: 67, level: "Towards A2" },
        overall: { score: 70, level: "A2" },
      },
      {
        name: "Victoria Trinidad Lazo Aguilar",
        rut: "245724292",
        listening: { score: 84, level: "A2" },
        reading: { score: 80, level: "A2" },
        writing: { score: 87, level: "A2" },
        speaking: { score: 60, level: "Towards A2" },
        overall: { score: 78, level: "A2" },
      },
      {
        name: "Amanda Sofía Lukacs Muñoz",
        rut: "24377067K",
        listening: { score: 80, level: "A2" },
        reading: { score: 83, level: "A2" },
        writing: { score: 83, level: "A2" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 85, level: "A2" },
      },
      {
        name: "Isidora Ignacia Lynch Varela",
        rut: "24387808K",
        listening: { score: 52, level: "Towards A2" },
        reading: { score: 50, level: "Towards A2" },
        writing: { score: 50, level: "Towards A2" },
        speaking: { score: 0, level: "" },
        overall: { score: 0, level: "" },
      },
      {
        name: "Isabella Manrique Huayna",
        rut: "244772773",
        listening: { score: 84, level: "A2" },
        reading: { score: 77, level: "A2" },
        writing: { score: 50, level: "Towards A2" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 76, level: "A2" },
      },
      {
        name: "Fernando Daniel Martín Valenzuela",
        rut: "245264003",
        listening: { score: 88, level: "A2" },
        reading: { score: 47, level: "Towards A2" },
        writing: { score: 47, level: "Towards A2" },
        speaking: { score: 0, level: "" },
        overall: { score: 0, level: "" },
      },
      {
        name: "Tomás Ignacio Maturana Cuevas",
        rut: "24263893K",
        listening: { score: 64, level: "Towards A2" },
        reading: { score: 83, level: "A2" },
        writing: { score: 53, level: "Towards A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 72, level: "A2" },
      },
      {
        name: "Josefina Magdalena Mendez Bozar",
        rut: "243251095",
        listening: { score: 84, level: "A2" },
        reading: { score: 90, level: "Towards B1" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 84, level: "A2" },
      },
      {
        name: "Antonia Belen Orellana Zurita",
        rut: "245806566",
        listening: { score: 56, level: "Towards A2" },
        reading: { score: 33, level: "A1" },
        writing: { score: 40, level: "A1" },
        speaking: { score: 73, level: "A2" },
        overall: { score: 51, level: "Towards A2" },
      },
      {
        name: "Emilia Fernanda Orellana Zurita",
        rut: "245806787",
        listening: { score: 64, level: "Towards A2" },
        reading: { score: 70, level: "A2" },
        writing: { score: 60, level: "Towards A2" },
        speaking: { score: 73, level: "A2" },
        overall: { score: 67, level: "Towards A2" },
      },
      {
        name: "Diego David Ramirez Escalante",
        rut: "253190345",
        listening: { score: 80, level: "A2" },
        reading: { score: 93, level: "Towards B1" },
        writing: { score: 63, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 84, level: "A2" },
      },
      {
        name: "Emilia Antonia Ramos Hayes",
        rut: "244748058",
        listening: { score: 44, level: "A1" },
        reading: { score: 53, level: "Towards A2" },
        writing: { score: 43, level: "A1" },
        speaking: { score: 67, level: "Towards A2" },
        overall: { score: 52, level: "Towards A2" },
      },
      {
        name: "Violetta Ruiz Doria",
        rut: "273790047",
        listening: { score: 84, level: "A2" },
        reading: { score: 83, level: "A2" },
        writing: { score: 63, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 83, level: "A2" },
      },
      {
        name: "Pamela Alondra Sahid Morales",
        rut: "245464967",
        listening: { score: 72, level: "A2" },
        reading: { score: 73, level: "A2" },
        writing: { score: 67, level: "Towards A2" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 76, level: "A2" },
      },
      {
        name: "Vicente Agustín Sonnleitner Muñoz",
        rut: "24538405K",
        listening: { score: 88, level: "A2" },
        reading: { score: 87, level: "A2" },
        writing: { score: 50, level: "Towards A2" },
        speaking: { score: 100, level: "Towards B1" },
        overall: { score: 81, level: "A2" },
      },
      {
        name: "Isidora Catalina Soto Lopez",
        rut: "245195818",
        listening: { score: 64, level: "Towards A2" },
        reading: { score: 43, level: "A1" },
        writing: { score: 70, level: "A2" },
        speaking: { score: 87, level: "A2" },
        overall: { score: 66, level: "Towards A2" },
      },
      {
        name: "Cristobal Mateo Vega Acosta",
        rut: "242977866",
        listening: { score: 80, level: "A2" },
        reading: { score: 83, level: "A2" },
        writing: { score: 100, level: "Towards B1" },
        speaking: { score: 93, level: "Towards B1" },
        overall: { score: 89, level: "A2" },
      },
      {
        name: "Daniel Alen Videla Catriñir",
        rut: "245204337",
        listening: { score: 56, level: "Towards A2" },
        reading: { score: 43, level: "A1" },
        writing: { score: 50, level: "Towards A2" },
        speaking: { score: 73, level: "A2" },
        overall: { score: 56, level: "Towards A2" },
      },
    ],
  },
  "5B": {
    "courseName": "Quinto B",
    "students": [
      {
        "name": "Abarca Rojas María Olivia",
        "rut": "246859698",
        "listening": { "score": 92, "level": "" },
        "reading": { "score": 67, "level": "" },
        "writing": { "score": 67, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 82, "level": "Nivel consolidado" }
      },
      {
        "name": "Alarcón Saavedra Emma Victoria",
        "rut": "248634715",
        "listening": { "score": 68, "level": "" },
        "reading": { "score": 77, "level": "" },
        "writing": { "score": 77, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 82, "level": "Nivel consolidado" }
      },
      {
        "name": "Arroyo Moya Tomás Ignacio",
        "rut": "248268425",
        "listening": { "score": 72, "level": "" },
        "reading": { "score": 52, "level": "" },
        "writing": { "score": 52, "level": "" },
        "speaking": { "score": 53, "level": "" },
        "overall": { "score": 59, "level": "Nivel intermedio" }
      },
      {
        "name": "Avaria Matamala Tomas",
        "rut": "246154236",
        "listening": { "score": 92, "level": "" },
        "reading": { "score": 67, "level": "" },
        "writing": { "score": 67, "level": "" },
        "speaking": { "score": 93, "level": "" },
        "overall": { "score": 84, "level": "Nivel consolidado" }
      },
      {
        "name": "Campos Rivera Javiera Isidora",
        "rut": "246257310",
        "listening": { "score": 84, "level": "" },
        "reading": { "score": 67, "level": "" },
        "writing": { "score": 67, "level": "" },
        "speaking": { "score": 93, "level": "" },
        "overall": { "score": 81, "level": "Nivel consolidado" }
      },
      {
        "name": "Castellanos Rodriguez Jorge Alejandro",
        "rut": "258382277",
        "listening": { "score": 72, "level": "" },
        "reading": { "score": 73, "level": "" },
        "writing": { "score": 73, "level": "" },
        "speaking": { "score": 67, "level": "" },
        "overall": { "score": 71, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Fernández Vidal Josefina Francisca",
        "rut": "248424370",
        "listening": { "score": 64, "level": "" },
        "reading": { "score": 63, "level": "" },
        "writing": { "score": 63, "level": "" },
        "speaking": { "score": 80, "level": "" },
        "overall": { "score": 69, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Fuentes Osorio Victoria Sofía",
        "rut": "246684499",
        "listening": { "score": 80, "level": "" },
        "reading": { "score": 79, "level": "" },
        "writing": { "score": 79, "level": "" },
        "speaking": { "score": 53, "level": "" },
        "overall": { "score": 71, "level": "Nivel satisfactorio" }
      },
      {
        "name": "González Barraza María Ignacia",
        "rut": "245929226",
        "listening": { "score": 96, "level": "" },
        "reading": { "score": 92, "level": "" },
        "writing": { "score": 92, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 96, "level": "Nivel consolidado" }
      },
      {
        "name": "Hernández Cepeda Maite Agustina",
        "rut": "246879869",
        "listening": { "score": 76, "level": "" },
        "reading": { "score": 71, "level": "" },
        "writing": { "score": 71, "level": "" },
        "speaking": { "score": 80, "level": "" },
        "overall": { "score": 76, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Hernández Rodríguez Raimundo Patricio",
        "rut": "245410522",
        "listening": { "score": 72, "level": "" },
        "reading": { "score": 52, "level": "" },
        "writing": { "score": 52, "level": "" },
        "speaking": { "score": 73, "level": "" },
        "overall": { "score": 66, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Herrera Beltran Amelia Lucia",
        "rut": "248083409",
        "listening": { "score": 64, "level": "" },
        "reading": { "score": 54, "level": "" },
        "writing": { "score": 54, "level": "" },
        "speaking": { "score": 80, "level": "" },
        "overall": { "score": 66, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Jara Cornejo Florencia Isidora",
        "rut": "247839283",
        "listening": { "score": 68, "level": "" },
        "reading": { "score": 46, "level": "" },
        "writing": { "score": 46, "level": "" },
        "speaking": { "score": 47, "level": "" },
        "overall": { "score": 53, "level": "Nivel intermedio" }
      },
      {
        "name": "Mancilla Durand Aneley Asiri",
        "rut": "246670374",
        "listening": { "score": 80, "level": "" },
        "reading": { "score": 50, "level": "" },
        "writing": { "score": 50, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 72, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Medel Fuentes Rafaela Sofía",
        "rut": "248507713",
        "listening": { "score": 68, "level": "" },
        "reading": { "score": 35, "level": "" },
        "writing": { "score": 35, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 68, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Mondaca Guzmán Nicolas Andrés",
        "rut": "24747451K",
        "listening": { "score": 68, "level": "" },
        "reading": { "score": 25, "level": "" },
        "writing": { "score": 25, "level": "" },
        "speaking": { "score": 53, "level": "" },
        "overall": { "score": 49, "level": "Nivel intermedio" }
      },
      {
        "name": "Monjes Astorga Rocío Antonia",
        "rut": "247226826",
        "listening": { "score": 84, "level": "" },
        "reading": { "score": 71, "level": "" },
        "writing": { "score": 71, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 80, "level": "Nivel consolidado" }
      },
      {
        "name": "Morales Vera Francisco Salomón",
        "rut": "246142785",
        "listening": { "score": 72, "level": "" },
        "reading": { "score": 42, "level": "" },
        "writing": { "score": 42, "level": "" },
        "speaking": { "score": 67, "level": "" },
        "overall": { "score": 60, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Ocares Morales Tomás Ricardo",
        "rut": "249296805",
        "listening": { "score": 52, "level": "" },
        "reading": { "score": 27, "level": "" },
        "writing": { "score": 27, "level": "" },
        "speaking": { "score": 60, "level": "" },
        "overall": { "score": 46, "level": "Nivel intermedio" }
      },
      {
        "name": "Olivero Fredes Catalina Isabel",
        "rut": "246243417",
        "listening": { "score": 80, "level": "" },
        "reading": { "score": 46, "level": "" },
        "writing": { "score": 46, "level": "" },
        "speaking": { "score": 73, "level": "" },
        "overall": { "score": 66, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Picero Silva Felipe Martín",
        "rut": "248035846",
        "listening": { "score": 84, "level": "" },
        "reading": { "score": 63, "level": "" },
        "writing": { "score": 63, "level": "" },
        "speaking": { "score": 67, "level": "" },
        "overall": { "score": 71, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Pino Iturra Mateo Emiliano",
        "rut": "246297819",
        "listening": { "score": 56, "level": "" },
        "reading": { "score": 25, "level": "" },
        "writing": { "score": 25, "level": "" },
        "speaking": { "score": 67, "level": "" },
        "overall": { "score": 49, "level": "Nivel intermedio" }
      },
      {
        "name": "Polverelli Castro Javiera Amalia",
        "rut": "248998318",
        "listening": { "score": 76, "level": "" },
        "reading": { "score": 48, "level": "" },
        "writing": { "score": 48, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 70, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Roselló Aceituno Emma Zoe",
        "rut": "247825398",
        "listening": { "score": 88, "level": "" },
        "reading": { "score": 77, "level": "" },
        "writing": { "score": 77, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 84, "level": "Nivel consolidado" }
      },
      {
        "name": "Salinas Camilo Samuel Alexis",
        "rut": "24660357K",
        "listening": { "score": 84, "level": "" },
        "reading": { "score": 65, "level": "" },
        "writing": { "score": 65, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 83, "level": "Nivel consolidado" }
      },
      {
        "name": "Sánchez Soto Josefa Antonia",
        "rut": "248182040",
        "listening": { "score": 56, "level": "" },
        "reading": { "score": 33, "level": "" },
        "writing": { "score": 33, "level": "" },
        "speaking": { "score": 40, "level": "" },
        "overall": { "score": 43, "level": "Nivel intermedio" }
      },
      {
        "name": "Sandoval Díaz Alonso Bautista",
        "rut": "248717866",
        "listening": { "score": 60, "level": "" },
        "reading": { "score": 31, "level": "" },
        "writing": { "score": 31, "level": "" },
        "speaking": { "score": 67, "level": "" },
        "overall": { "score": 53, "level": "Nivel intermedio" }
      },
      {
        "name": "Soler Camacho Samuel Daniel",
        "rut": "247737251",
        "listening": { "score": 72, "level": "" },
        "reading": { "score": 44, "level": "" },
        "writing": { "score": 44, "level": "" },
        "speaking": { "score": 93, "level": "" },
        "overall": { "score": 70, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Thiele Marin Isabella",
        "rut": "249220345",
        "listening": { "score": 72, "level": "" },
        "reading": { "score": 42, "level": "" },
        "writing": { "score": 42, "level": "" },
        "speaking": { "score": 73, "level": "" },
        "overall": { "score": 62, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Torres Mardones Martín Antonio",
        "rut": "247367519",
        "listening": { "score": 76, "level": "" },
        "reading": { "score": 50, "level": "" },
        "writing": { "score": 50, "level": "" },
        "speaking": { "score": 80, "level": "" },
        "overall": { "score": 69, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Urrutia Neira Marcela Fernanda",
        "rut": "248945834",
        "listening": { "score": 76, "level": "" },
        "reading": { "score": 60, "level": "" },
        "writing": { "score": 60, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 79, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Luengo Fernández Tomás Alfonso",
        "rut": "247805427",
        "listening": { "score": 0, "level": "" },
        "reading": { "score": 0, "level": "" },
        "writing": { "score": 0, "level": "" },
        "speaking": { "score": 93, "level": "" },
        "overall": { "score": 0, "level": "" }
      },
      {
        "name": "Demayo Guajardo Sofia Ignacia",
        "rut": "",
        "listening": { "score": 0, "level": "" },
        "reading": { "score": 0, "level": "" },
        "writing": { "score": 0, "level": "" },
        "speaking": { "score": 0, "level": "" },
        "overall": { "score": 0, "level": "" }
      },
      {
        "name": "Mora Cerda Martina Elena",
        "rut": "248322608",
        "listening": { "score": 0, "level": "" },
        "reading": { "score": 0, "level": "" },
        "writing": { "score": 0, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 0, "level": "" }
      }
    ]
  },
  "5C": {
    "courseName": "Quinto C",
    "students": [
      {
        "name": "Adriazola López Renato Fabián",
        "rut": "247289496",
        "listening": { "score": 96, "level": "" },
        "reading": { "score": 88, "level": "" },
        "writing": { "score": 88, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 90, "level": "Nivel consolidado" }
      },
      {
        "name": "Ayon Rubi Fabiana Lucia",
        "rut": "1006456703",
        "listening": { "score": 92, "level": "" },
        "reading": { "score": 92, "level": "" },
        "writing": { "score": 92, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 95, "level": "Nivel consolidado" }
      },
      {
        "name": "Bradanovic Femenias Ema Sofia",
        "rut": "24604600K",
        "listening": { "score": 96, "level": "" },
        "reading": { "score": 60, "level": "" },
        "writing": { "score": 60, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 85, "level": "Nivel consolidado" }
      },
      {
        "name": "Bravo Lagos Antonia Carolina",
        "rut": "246807116",
        "listening": { "score": 88, "level": "" },
        "reading": { "score": 67, "level": "" },
        "writing": { "score": 67, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 85, "level": "Nivel consolidado" }
      },
      {
        "name": "Bustamante Sepúlveda Lucas Esteban",
        "rut": "247478574",
        "listening": { "score": 96, "level": "" },
        "reading": { "score": 77, "level": "" },
        "writing": { "score": 77, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 87, "level": "Nivel consolidado" }
      },
      {
        "name": "Cabrera Yau Santiago Alonso",
        "rut": "246721378",
        "listening": { "score": 96, "level": "" },
        "reading": { "score": 92, "level": "" },
        "writing": { "score": 92, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 96, "level": "Nivel consolidado" }
      },
      {
        "name": "Campos Tobar Benito Ignacio",
        "rut": "246271178",
        "listening": { "score": 0, "level": "" },
        "reading": { "score": 0, "level": "" },
        "writing": { "score": 0, "level": "" },
        "speaking": { "score": 73, "level": "" },
        "overall": { "score": 24, "level": "Nivel incipiente" }
      },
      {
        "name": "Castaldi Pinet Matteo Stefano",
        "rut": "246291713",
        "listening": { "score": 76, "level": "" },
        "reading": { "score": 50, "level": "" },
        "writing": { "score": 50, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 71, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Castillo Jaña Santiago Ignacio",
        "rut": "248027916",
        "listening": { "score": 96, "level": "" },
        "reading": { "score": 77, "level": "" },
        "writing": { "score": 77, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 91, "level": "Nivel consolidado" }
      },
      {
        "name": "Cárcamo Sarmiento Aranza Emilia",
        "rut": "246086028",
        "listening": { "score": 72, "level": "" },
        "reading": { "score": 48, "level": "" },
        "writing": { "score": 48, "level": "" },
        "speaking": { "score": 73, "level": "" },
        "overall": { "score": 64, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Diaz Garrido Gaspar Enrique",
        "rut": "246718040",
        "listening": { "score": 92, "level": "" },
        "reading": { "score": 58, "level": "" },
        "writing": { "score": 58, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 79, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Durán Salas Gaspar Andrés",
        "rut": "246889503",
        "listening": { "score": 92, "level": "" },
        "reading": { "score": 48, "level": "" },
        "writing": { "score": 48, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 76, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Espinoza Bravo Javier Alonso",
        "rut": "247684484",
        "listening": { "score": 80, "level": "" },
        "reading": { "score": 71, "level": "" },
        "writing": { "score": 71, "level": "" },
        "speaking": { "score": 80, "level": "" },
        "overall": { "score": 77, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Fagalde Díaz Maite Trinidad",
        "rut": "247935525",
        "listening": { "score": 84, "level": "" },
        "reading": { "score": 52, "level": "" },
        "writing": { "score": 52, "level": "" },
        "speaking": { "score": 73, "level": "" },
        "overall": { "score": 70, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Fuster Benavides Rafaela Paz",
        "rut": "247276750",
        "listening": { "score": 76, "level": "" },
        "reading": { "score": 85, "level": "" },
        "writing": { "score": 85, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 87, "level": "Nivel consolidado" }
      },
      {
        "name": "Gurmandi Freijo Isabella",
        "rut": "245895038",
        "listening": { "score": 100, "level": "" },
        "reading": { "score": 90, "level": "" },
        "writing": { "score": 90, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 97, "level": "Nivel consolidado" }
      },
      {
        "name": "Jara Cáceres Agustina",
        "rut": "246593043",
        "listening": { "score": 72, "level": "" },
        "reading": { "score": 50, "level": "" },
        "writing": { "score": 50, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 70, "level": "Nivel satisfactorio" }
      },
      {
        "name": "León Muñoz Florencia Isabella",
        "rut": "249078891",
        "listening": { "score": 72, "level": "" },
        "reading": { "score": 52, "level": "" },
        "writing": { "score": 52, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 75, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Lillo Palma Martina Paz",
        "rut": "245586825",
        "listening": { "score": 80, "level": "" },
        "reading": { "score": 42, "level": "" },
        "writing": { "score": 42, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 74, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Mansilla Acosta Diego Alejandro",
        "rut": "245964501",
        "listening": { "score": 92, "level": "" },
        "reading": { "score": 69, "level": "" },
        "writing": { "score": 69, "level": "" },
        "speaking": { "score": 93, "level": "" },
        "overall": { "score": 85, "level": "Nivel consolidado" }
      },
      {
        "name": "Mardones Acevedo Javier Alonso",
        "rut": "247734686",
        "listening": { "score": 88, "level": "" },
        "reading": { "score": 50, "level": "" },
        "writing": { "score": 50, "level": "" },
        "speaking": { "score": 100, "level": "" },
        "overall": { "score": 79, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Maturana Cuevas Dominga Jesús",
        "rut": "247133283",
        "listening": { "score": 84, "level": "" },
        "reading": { "score": 50, "level": "" },
        "writing": { "score": 50, "level": "" },
        "speaking": { "score": 87, "level": "" },
        "overall": { "score": 74, "level": "Nivel satisfactorio" }
      },
      {
        "name": "Orchard Quiroz Santiago Ignacio",
        "rut": "245421087",
        "listening": { "score": 48, "level": "" },
        "reading": { "score": 21, "level": "" },
        "writing": { "score": 21, "level": "" },
        "speaking": { "score": 40, "level": "" },
        "overall": { "score": 36, "level": "Nivel incipiente" }
      },
      {
        "name": "Pseli Durán Jorge Alexander",
        "rut": "248718382",
        "listening": { "score": 92, "level": "" },
        "reading": { "score": 54, "level": "" },
        "writing": { "score": 54, "level": "" },
        "speaking": { "score": 93, "level": "" },
        "overall": { "score": 80, "level": "Nivel consolidado" }
      }
    ]
  }


};

// Función auxiliar para obtener la lista de cursos disponibles
export const getAvailableCourses = () => {
  return Object.keys(coursesData).map((courseId) => ({
    id: courseId,
    name: coursesData[courseId].courseName,
  }));
};

// Función auxiliar para buscar un estudiante por RUT en un curso específico
export const findStudentByRut = (courseId, rut) => {
  const course = coursesData[courseId];
  if (!course) return null;

  return course.students.find(
    (student) => student.rut.toLowerCase() === rut.toLowerCase().trim()
  );
};

// Función auxiliar para obtener estadísticas del curso
export const getCourseStats = (courseId) => {
  const course = coursesData[courseId];
  if (!course) return null;

  const students = course.students;
  const totalStudents = students.length;

  const levelCounts = {
    A1: 0,
    A2: 0,
    B1: 0,
    "Towards B2": 0,
    B2: 0,
  };

  students.forEach((student) => {
    const level = student.overall.level;
    if (Object.prototype.hasOwnProperty.call(levelCounts, level)) {
      levelCounts[level]++;
    }
  });

  const avgScore =
    students.reduce((sum, s) => sum + s.overall.score, 0) / totalStudents;

  return {
    totalStudents,
    levelCounts,
    averageScore: Math.round(avgScore),
  };
};
